[mypy]
python_version = 3.12

# Ne scanne que ton code
files = src

# Ta ferme pour les sujets qui t’embêtent aujourd’hui
disable_error_code = misc,no-untyped-def,no-any-return,type-arg

# On évite le bruit
ignore_missing_imports = True
follow_imports = silent
warn_unused_ignores = False
allow_redefinition = True
show_error_codes = True
pretty = True

# Exclusions dossiers bruit
exclude = (?x)(
    ^tests/|
    ^docs/|
    ^htmlcov/|
    ^build/|
    ^dist/
)

# (Option) Mute temporaire de zones très bruyantes
[mypy-src.hanuman.api.core.*]
ignore_errors = True

[mypy-src.hanuman.api.orchestrations.*]
ignore_errors = True
