[mypy]
python_version = 3.12
strict = False

# pragmatique
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_incomplete_stub = True
warn_no_return = True

# nouvelle manière de désactiver les “untyped-decorator”
disable_error_code = untyped-decorator

[mypy-tests.*]
ignore_errors = True
