version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  rich:
    format: "%(message)s"

  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
    datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout


  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/hanuman.log
    when: midnight
    backupCount: 7
    encoding: utf8

  error_file:
    class: logging.FileHandler
    level: ERROR
    formatter: json
    filename: logs/hanuman_error.log
    encoding: utf8

loggers:
  hanuman:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, error_file]
